name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm install
      - name: Run Jest tests
        run: npm run test
      - name: Start server
        run: npm run start:dev &
      - name: Wait for server
        run: sleep 5
